### PR TITLE
skip the validation of parentId on deletion

### PR DESCRIPTION
**Pull request by nrob81**
#77 Using a model scenario for moderation will fix the issue, when searching for a parent comment that is already deleted.

### CODE REVIEW

**Comment by ihorchepurnyi** [comment]
Hi, can you apply `php-cs-fixer` to your pull request?

**Comment by ihorchepurnyi** [comment]
`vendor/bin/php-cs-fixer fix`

**Comment by nrob81** [comment]
hello, yes sure

**Comment by nrob81** [comment]
ok, i had fixed it with the php-cs-fixer. may i create a new pull request?

**Comment by ihorchepurnyi** [comment]
Yes, of course. Please, push your changes

**Comment by nrob81** [comment]
huhhh. :)

**Comment by ihorchepurnyi** [comment]
Thanks

**Pull request merged**
